### PR TITLE
ApolloClient does not delay the application becoming stable

### LINKED ISSUE #2251: apollo-angular prevents Zone from becoming stable
**Describe the bug**

When apollo-angular is used with Angular SSR and a GraphQL query is made from an `APP_INITIALIZER` then Angular hydration is delayed by about 10 seconds.
This happens, because `ApolloClient` [uses `setTimeout`](https://github.com/apollographql/apollo-client/blob/77373cd8bdbd2dbcb3b698e88113719fd95ebfc3/src/core/ApolloClient.ts#L311-L339) when constructed to suggest you to use its devtools. This `setTimeout` prevents Zone from becoming stable, delaying hydration.

**To Reproduce**
Use apollo-angular from within an `APP_INITIALIZER` in an Angular App using Angular 17 SSR. Observe the "Angular hydrated ..." message being delayed.

**Expected behavior**

apollo-angular should not delay hydration / `ApplicationRef#isStable`.

**Environment:**

```
├── @angular/cli@17.3.5
├── @angular/core@17.3.5
├── @apollo/client@3.10.1
├── apollo-angular@7.0.0
├── graphql@16.8.1
└── typescript@5.4.5
```

**Additional context**

To fix this, the call to the `ApolloClient` constructor should be wrapped in `zone.runOutsideAngular`. I have worked around this problem like so:
```ts
export function provideGraphql(): EnvironmentProviders {
    return makeEnvironmentProviders([
        {
            provide: Apollo,
            useFactory: () => {
                // Apollo must be created outside the Angular Zone, because ApolloClient starts a `setTimeout` for its
                // devtools connection
                // this setTimeout prevents NgZone from becoming stable
                const zone = inject(NgZone);
                const options = inject(APOLLO_OPTIONS, { optional: true }) ?? undefined;
                const namedOptions = inject(APOLLO_NAMED_OPTIONS, { optional: true }) ?? undefined;
                const flags = inject(APOLLO_FLAGS, { optional: true }) ?? undefined;
                // Note the following line:
                return zone.runOutsideAngular(() => new Apollo(zone, options, namedOptions, flags));
            },
        },
        {
            provide: APOLLO_OPTIONS,
            useFactory: () => {
                const httpLink = inject(HttpLink);
                return {
                    link: httpLink.create({ uri }),
                    cache: new InMemoryCache(),
                } satisfies ApolloClientOptions<unknown>;
            },
        },
    ]);
}

### PR DESCRIPTION
**Pull request by PowerKiKi**
Otherwise, we might encounter a delay of 10 seconds, and this might lead to suboptimal experience as described in https://angular.io/errors/NG0506

Fixes #2251

### CODE REVIEW

**Comment by PowerKiKi** [comment]
@diesieben07, thanks for the reproduction case. I can see from https://angular.io/errors/NG0506 that #2251 unnecessarily delays DOM clean up. While I am not quite sure this could have such an catastrophic effect, we might as well avoid it by following your suggestion.

You would you mind testing the alpha release in your real-world project and report if everything goes smoothly via `npm i apollo-angular@7.0.1-alpha-20240502094658-7ac65bdaeddc99e9741afc26b254d357f35d248c` ?

**Comment by diesieben07** [comment]
@PowerKiKi Thank you for the prompt fix. The problem no longer occurs in our (internal) real world project with `npm i apollo-angular@7.0.1-alpha-20240502094658-7ac65bdaeddc99e9741afc26b254d357f35d248c`.
So this PR fixes the problem :+1:

**Comment by PowerKiKi** [comment]
Released in https://github.com/kamilkisiela/apollo-angular/releases/tag/apollo-angular%407.0.1

**Comment by diesieben07** [comment]
Thank you, works great!

**Pull request merged**
