### PR TITLE
Bumping @angular/core dependency

### PR DESCRIPTION
**Pull request by quinnjr**
Bumping the `@angular/core` dependency to allow for use with Angular v14.

### Checklist:

- [ ] If this PR is a new feature, please reference a discussion where a consensus about the design was reached (not necessary for small changes)
- [ ] Make sure all of the significant new logic is covered by tests
- [ ] Try to include the Pull Request inside of CHANGELOG.md

### CODE REVIEW

**Comment by CemYil03** [comment]
Would be super important to get this working quickly 😅

**Comment by perjerz** [comment]
Please merge.

**Comment by quinnjr** [comment]
Can we please get this merged soon?

**Comment by quinnjr** [comment]
https://github.com/kamilkisiela/apollo-angular/pull/1794

**Pull request closed without merging**
