### PR TITLE
fix type

### PR DESCRIPTION
**Pull request by RobinKamps**
### Checklist:

- [ ] If this PR is a new feature, please reference a discussion where a consensus about the design was reached (not necessary for small changes)
- [ ] Make sure all of the significant new logic is covered by tests
- [ ] Try to include the Pull Request inside of CHANGELOG.md

### CODE REVIEW

**Comment by RobinKamps** [comment]
possible fix for #1818

**Comment by laudebugs** [comment]
I've seen this issue come up recently as well. Thanks for the fix!

**Comment by jbelien** [comment]
This for this PR. It indeed seems to fix an issue where TypeScript is complaining about the `data` property on `MutationResult`.
> La propriété 'data' n'existe pas sur le type 'MutationResult<{ emergency_plan: EmergencyPlan; }>'.ts(2339)

**Comment by PowerKiKi** [comment]
https://github.com/kamilkisiela/apollo-angular/issues/1818#issuecomment-1277348269 is already closed as solved. Is this PR still needed ?

**Comment by RobinKamps** [comment]
Fixed - not needed anymore

**Pull request closed without merging**
