### PR TITLE
Support rxjs 7

### PR DESCRIPTION
**Pull request by PowerKiKi**
Since Angular 12.2 it is possible to opt-in rxjs 7.
So we allow it in apollo-angular too.

### Checklist:

- [ ] If this PR is a new feature, please reference a discussion where a consensus about the design was reached (not necessary for small changes)
- [x] Make sure all of the significant new logic is covered by tests
- [x] Try to include the Pull Request inside of CHANGELOG.md

### CODE REVIEW

**Comment by ruizmarc** [comment]
Hi! Any plans to merge this now that angular 13 is out with rxjs 7 as default?

**Comment by SerdarN92** [comment]
We really need this .. how is the status? I see that nobody is added as assignees. @PowerKiKi

**Comment by PowerKiKi** [comment]
@SerdarN92, there's nothing more I can do, until we get news from Kamil. Until then, and as a workaround, you can still use this lib with Rxjs 7 and ignore the warning.

**Comment by gilgardosh** [comment]
added as part of #1729

**Pull request closed without merging**
