### PR TITLE
Angular 14

### PR DESCRIPTION
**Pull request by kamilkisiela**
https://github.com/kamilkisiela/apollo-angular/issues/1789#issuecomment-1168562501

### CODE REVIEW

**Review by kimarudg — APPROVED** [review]
This PR looks Ok.
Can it land now?

**Comment by kamilkisiela** [comment]
https://github.com/kamilkisiela/apollo-angular/issues/1789#issuecomment-1168562501

**Comment by bendehghan** [comment]
Hi guys,
Are we any closer to this going through?
Thanks,
Ben

**Comment by bendehghan** [comment]
Hi guys,

This package is obviously critical to anyone using angular and graphql. But with months after angular 14 release we still don't have a working solution. 

Just wondering if the issue is with not having enough time to figure out the problem because of other commitments or that the problem is particularly hard and lots of time has been spent with no solution? And what can we do to help either way. 

The one thing we do need is a way forward.

I realize this is community effort and we all really appreciate the effort so far. But running a business on shaky ground is hard. I'm trying to make a decision on wether to give up on this and find a different solution if the issue is that this package is not going to be maintained anymore. If that's the case, I'd rather just spend some time and redo some work on my side and switch.

If the answer is to switch, does anyone have a solution they recommend. Is there a way to use graphql in angular without this package?

Thank you guys

**Comment by kamilkisiela** [comment]
> Hi guys,
> 
> This package is obviously critical to anyone using angular and graphql. But with months after angular 14 release we still don't have a working solution. 
> 
> Just wondering if the issue is with not having enough time to figure out the problem because of other commitments or that the problem is particularly hard and lots of time has been spent with no solution? And what can we do to help either way. 
> 
> The one thing we do need is a way forward.
> 
> I realize this is community effort and we all really appreciate the effort so far. But running a business on shaky ground is hard. I'm trying to make a decision on wether to give up on this and find a different solution if the issue is that this package is not going to be maintained anymore. If that's the case, I'd rather just spend some time and redo some work on my side and switch.
> 
> If the answer is to switch, does anyone have a solution they recommend. Is there a way to use graphql in angular without this package?
> 
> Thank you guys 
> 
> 
> 
> 

As I said multiple times and even commented here in this Pull Request, I'm waiting for some contributions from community. If it bothers you, please switch to a different library. My PR upgraded this library to Angular 14, just can't figure out tests. Unit and integration tests are something that you probably do in your work, so feel free to help me and the community and fix it for us next time instead of complaining :)

There's one PR that solved the tests issue and is ready for a review for almost 8 days, I will spend my free time to review it soon. 

Thank you

**Comment by bendehghan** [comment]
Yes, we're trying to move on if we can. My question was from the community on suggestions for how and which library. It's not really sustainable to have major dependencies on packages with unknown amounts of time for fixes for major upgrades. It's not like Angular 14 just showed up out of nowhere. We just wrongly assumed this was a well supported library. It's not the first time we had this issue. Same thing happened with Angular 13.

It would help if you are clear about your time commitments otherwise. We shouldn't rely on you spending your free time on this. You should enjoy your free time. :) Or setup a patreon or ko-fi or the like if it helps.

**Comment by kamilkisiela** [comment]
#1803

**Pull request closed without merging**
