### PR TITLE
Cover batched XHR cancelling with tests

### PR DESCRIPTION
**Pull request by PowerKiKi**
### Checklist:

- [ ] If this PR is a new feature, please reference a discussion where a consensus about the design was reached (not necessary for small changes)
- [x] Make sure all of the significant new logic is covered by tests
- [ ] Try to include the Pull Request inside of CHANGELOG.md

This is dependent on https://github.com/apollographql/apollo-client/pull/9248, so it is not strictly specific to `apollo-angular`, but it seemed important to ensure that this package does indeed allow to cancel XHR even when batching is enabled.

There is no changelog entries, because there not change at all for end-users.

It should only be merged after a new apollo-client is released (and after updating our lock file).

### CODE REVIEW

**Comment by PowerKiKi** [comment]
Now that `@apollo/client` [3.6.0](https://github.com/apollographql/apollo-client/releases/tag/v3.6.0) has been released, this PR can be reviewed and merged too.

**Comment by PowerKiKi** [comment]
@kamilkisiela since this is mostly adding new test cases, it should be relatively fast to review. Do you think it could get merged ?

**Comment by PowerKiKi** [comment]
Rebased.

Because CI pipeline changed after this PR was created it looks like some jobs are still pending. But actually everything that need to pass does indeed pass.

@kamilkisiela would you have an opportunity to review this ?

**Comment by kamilkisiela** [comment]
@PowerKiKi do you want to maintain the library? :)

**Comment by kamilkisiela** [comment]
say Yes and I click "merge" :)

**Comment by kamilkisiela** [comment]
@PowerKiKi do you use Slack? If so, are you okay with joining The Guild's #apollo-angular channel? It would be easier to discuss things.

In short, I'm not stepping down, it's just that I'm too busy with other things and this project needs some love.
ApolloModule was re-introduced to enable back the lazy loading. Also, using `APOLLO_OPTIONS` was out of sync with initialization of `Apollo` service, same for `APOLLO_FLAGS`.

**Comment by PowerKiKi** [comment]
I don't usually use slack, but I will if necessary. I can't find the URL for Slack anywhere though....

**Comment by kamilkisiela** [comment]
I need to invite you, it's not a public slack. Can share your email address with me, over email (to not expose it here)?

**Pull request merged**
