### PR TITLE
Support angular 17 and drop 14,15,16

### PR DESCRIPTION
**Pull request by rezoled**
### Checklist:
- [x] Make sure all the significant new logic is covered by tests

### CODE REVIEW

**Comment by PowerKiKi** [comment]
my guess is that you schematics are trying to inject module-things into a standalone app, thus producing non-compiling code. #2093 addresses this by (trying to) supporting both module or standalone app. But I stumble on further issues. I'd suggest you to make a PR against my PR if you are able to find a solution.

**Comment by rezoled** [comment]
Do we really want to be sure that ng add works correctly? isn't this Angular's job? why do we need to test if an angular cli command works correctly? this is the problem of the test, it checks for something that ng-cli abstracts away

**Comment by PowerKiKi** [comment]
> isn't this Angular's job?

Precisely, it is not Angular job. We have a non-trivial code in `packages/apollo-angular/schematics` that are meant to handle this. It is non-trivial because Angular does not provide a high-enough abstraction. Instead we need to juggle with quite a few things, and that makes it more fragile than it should be IMHO.

**Comment by rezoled** [comment]
So I ran all the commands from the test steps locally, and it seems to be working. any thoughts?

**Comment by rezoled** [comment]
> I'm not expert either. I've been reproducing
> 
> https://github.com/kamilkisiela/apollo-angular/blob/1fd2b6f9e4eaafcdb0acf577a072755099fbdb80/.github/workflows/main.yml#L116-L125
> 
> manually locally. It's a long feedback loop, but I didn't find a better way yet ...

Thanks, that helps. I ran the test locally and found the source of the problem:
1) Angular's new app generated app is standalone by default, so the prepare-e2e file which added an injection of apollo client did not add an import to the component of apollo module
2) cypress changed their default test, so prepare-e2e did no manage to modify the correct test and it failed because it was looking for content that did not exist.

I fixed prepare-e2e file for these scenarios and added a script to run the e2e locally.

**Comment by rezoled** [comment]
@kamilkisiela can we merge this? it's currently stopping devs from upgrading to Angular 17

**Comment by PowerKiKi** [comment]
Can you rebase this on top of my pr, branch `powerkiki`, so I have less code code to review when I get to review this, please?

**Comment by rezoled** [comment]
> Can you rebase this on top of my pr, branch `powerkiki`, so I have less code code to review when I get to review this, please?

There you go: https://github.com/kamilkisiela/apollo-angular/pull/2104

**Comment by PowerKiKi** [comment]
Superseded by #2093

**Pull request closed without merging**
